project:
  type: website
  output-dir: docs
  render:
    - Quarto/*.qmd

website:
  title: "Lion Coordination"
  navbar:
    left:
      - href: Quarto/results.qmd
        text: Results
      - href: Quarto/design.qmd
        text: Design
  

execute: 
  python-path: src